### ISSUE TITLE
DELETE a category does not remove corresponding items

### ISSUE THREAD

**Issue by Ungerfall** [Lostide/NetIntermediate#2]
Related to requirement
> Delete category (with the related items)

**Comment by Lostide** [comment]
Cascade delete automatically deletes dependent records or sets null to ForeignKey columns when the parent record is deleted in the database, according to the Entity Framework 6, which is installed to my project, try to check manually

**Comment by Lostide** [comment]
Cascade delete is enabled by default in Entity Framework for all types of relationships such as one-to-one, one-to-many and many-to-many.
